# Site settings
title: skim blog
motto: Happy Coding
email: rumex13@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Developer, Coding, Programming
baseurl: "" # the subpath of your site, e.g. /blog/
url: http://skim.kr # the base hostname & protocol for your site
author: skim
twitter_username: rumex13
github_username: SwimingKim

# Build settings
markdown: kramdown

disqus:
  id: "devskim"
